openapi: 3.0.3
info:
  title: Beauty salon booking - OpenAPI 3.0
  description: >-
    This is a Beauty Salon Booking Server based on the OpenAPI 3.0
    specification. 
  version: 1.0.0
tags:
  - name: appointment
    description: Beauty salon reservations
paths:
  /appointment:
    get:
      tags:
        - appointment
      summary: Get all appointments
      description: Get all appointments
      operationId: getAppointments
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid ID supplied
        '404':
          description: Appointment not found
        '405':
          description: Validation exception
    post:
      tags:
        - appointment
      summary: Add a new apointment to the Beauty Salon
      description: Add a new apointment to the Beauty Salon
      operationId: addAppointment
      requestBody:
        description: Add a new appointment to the beauty salon
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/xml:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Appointment'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                $ref: '#/components/schemas/Appointment'
        '405':
          description: Invalid input
  /appointment/{appointmentId}:
    get:
      tags:
        - appointment
      summary: Find appointment by ID
      description: Returns a single appointment
      operationId: getAppointmentById
      parameters:
        - name: appointmentId
          in: path
          description: ID of appointment to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid ID supplied
        '404':
          description: Appointment not found
    delete:
      tags:
        - appointment
      summary: Delete an appointment
      description: delete an appointment
      operationId: deleteAppointment
      parameters:
        - name: appointmentId
          in: path
          description: Appointment id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Invalid appointment id
    put:
      tags:
        - appointment
      summary: Update an existing appointment
      description: Update an existing appointment by Id
      operationId: updateAppointment
      requestBody:
        description: Update an existent appointment of the beauty salon
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/xml:
            schema:
              $ref: '#/components/schemas/Appointment'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Appointment'
        required: true
      parameters:
        - name: appointmentId
          in: path
          description: Appointment id to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid ID supplied
        '404':
          description: Appointment not found
        '405':
          description: Validation exception
    patch:
      tags:
        - appointment
      summary: Partially update an appointment at the beauty salon
      description: Partially update an appointment at the beauty salon
      operationId: patchAppointment
      requestBody:
        description: Update an existent appointment of the beauty salon
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentProperties'
          application/xml:
            schema:
              $ref: '#/components/schemas/AppointmentProperties'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AppointmentProperties'
        required: true
      parameters:
        - name: appointmentId
          in: path
          description: Appointment id to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid ID supplied
        '404':
          description: Appointment not found
        '405':
          description: Validation exception
  /appointment/{appointmentId}/reschedule:
    put:
      tags:
        - appointment
      summary: Reschedule an existing appointment
      description: Reschedule an existing appointment by Id
      operationId: rescheduleAppointment
      requestBody:
        description: Reschedule an existent appointment of the beauty salon
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentReschedule'
          application/xml:
            schema:
              $ref: '#/components/schemas/AppointmentReschedule'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AppointmentReschedule'
        required: true
      parameters:
        - name: appointmentId
          in: path
          description: Appointment id to update
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid ID supplied
        '404':
          description: Appointment not found
        '405':
          description: Validation exception
          
  /appointment/{service}: 
    get:
      tags:
        - appointment
      summary: Get all appointments by service
      description: Get all appointments by service
      operationId: getAppointmentsByService
      parameters:
        - name: service
          in: path
          description: Name of the service type to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '404':
          description: Service not found
  /appointment/{customerName}: 
    get:
      tags:
        - appointment
      summary: Get all appointments by customer
      description: Get all appointments by customer
      operationId: getAppointmentsByCustomer
      parameters:
        - name: customerName
          in: path
          description: Name of the customer to search for
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '404':
          description: Customer not found
  /appointment/{startDateTime}/{endDateTime}: 
    get:
      tags:
        - appointment
      summary: Get all appointments by time period
      description: Get all appointments by time period
      operationId: getAppointmentsByTimePeriod
      parameters:
        - name: startDateTime
          in: path
          description: Start date time
          required: true
          schema:
            type: string
        - name: endDateTime
          in: path
          description: End date time
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Appointment'
        '400':
          description: Invalid date format supplied
          
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        name:
          type: string
          example: Anne Korhonen
      xml:
        name: customer
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Facial treatments
      xml:
        name: category
        
    Service:
      type: string
      example: peeling
          
    StartDateTime:
      type: string
      example: '2022-11-20T15:28:55.304Z'
      
    EndDateTime:
      type: string
      example: '2022-11-20T15:28:55.304Z'
          
    AppointmentProperties:
      type: object
      properties:
        id:
          readOnly: true
          type: integer
          format: int64
          example: 10
        service:
           $ref: '#/components/schemas/Service'
        category:
          $ref: '#/components/schemas/Category'
        customer:
          $ref: '#/components/schemas/Customer'
        startDateTime:
          $ref: '#/components/schemas/StartDateTime'
        endDateTime:
          $ref: '#/components/schemas/EndDateTime'
      xml:
        name: appointmentProperties
        
    AppointmentRequiredProperties:
      type: object
      required:
        - service
        - category
        - customer
        - startDateTime
        - endDateTime
      
    Appointment:
      allOf: 
        -  $ref: '#/components/schemas/AppointmentProperties'
        -  $ref: '#/components/schemas/AppointmentRequiredProperties'
      xml:
        name: appointment
        
            
    AppointmentReschedule:
      type: object
      properties:
        startDateTime:
          $ref: '#/components/schemas/StartDateTime'
        endDateTime:
          $ref: '#/components/schemas/EndDateTime'
      xml:
        name: appointmentReservation
        
